### ISSUE TITLE
Serge workflow to translate .po files

### ISSUE THREAD

**Issue by imankulov** [evernote/serge#10]
Unfortunately, I still have issues trying to make serge work. This time I'm not quite sure what the workflow for translation .po files could be. Can you please help me to connect the dots.

## Repository layout

We have a repository with the following structure:

```
en/LC_MESSAGES/messages.pot
...
ar/LC_MESSAGES/messages.po
bg/LC_MESSAGES/messages.po
ru/LC_MESSAGES/messages.po
...
```

The `en` lang plays the role of a source language. Files in `lang/LC_MESSAGES/messages.po` are mostly translated.

## Serge configuration

Serge config file looks like this: [my_project.serge](https://github.com/evernote/serge/files/51136/my_project.txt). I put my repository inside `repos/my_project`, and translation files which Pootle operates with, live in `translations/my_project`.

## What I expect to have

At first sight, it looks a bit silly that we make Serge to parse .po files and store it in a different directory with the same format. But my initial goal was to make Serge apply changes from `en/.../messages.pot` to `lng/.../messages.po` for every language. Previously we did this job with `pootle update_against_templates`, but according to [new documentation](http://docs.translatehouse.org/projects/pootle/en/stable-2.7.3/features/templates.html), it's up to third-party tools to do this. I expected Serge to help me with that :)

## What I tried to do

Simple `serge pull` and `serge localize` didn't help. Quite the opposite, it replaced all translations in all files with msgids. The diff excerpt (result of the `serge localize` work).

```diff
@@ -38,7 +36,7 @@ msgstr ""
 #: tmpl/user/reset_password.mako:24
 #: tmpl/user/welcome.mako:53
 msgid "Best regards,"
-msgstr "С наилучшими пожеланиями,"
+msgstr "Best regards,"
```

I rolled back everything to initial state and removed the SQLite "translation memory" database. My next step was to try to import strings first. Results of the `serge import` weren't very satisfactory either.
![serge-import](https://cloud.githubusercontent.com/assets/75075/11569301/1ab4b0b6-99e9-11e5-9f31-2991890a1d7e.png)

Looks like Serge populates database with original strings for every language. The result of `serge localize` was the same as in previous case.

## What should I do?

I tried to make Serge work according to my expectations based on my best understanding of the Serge workflow. Can you please help me and tell me where I failed. Shouldn't I use Serge for that kind of work in the first place, or my workflow is wrong, or maybe there is a bug in Serge itself?

Grateful for any help. Ready to provide all sorts of extra information. Thanks!

**Comment by imankulov** [comment]
For the record, we made a workaround by applying merge operation manually with [pybabel update](http://babel.pocoo.org/docs/cmdline/#update)

**Comment by iafan** [comment]
Though importing translations from .po was supposed to be done with https://github.com/evernote/serge/commit/b2a3c7e3644a383aefb47bf93bcacd1ef840c904 commit, I just realized we need to do some extra processing since localized files contain translations in `msgstr` and not in `msgid`. My bad. I'll need to update my parser code to properly import translations from .po files (working on it right now).

Once this is done, you will need to import translations from .po files once again using `serge import`. When translations are in the database, doing subsequent `serge localize` will not revert your translations in localized files.

**Comment by imankulov** [comment]
Thanks for the update, Igor!

**Comment by iafan** [comment]
Ok, the parser has been adjusted; can you please try running `serge import` again against your .po files and examine the import HTML report?

Just a friendly reminder that for live troubleshooting it make sense to also use our #serge IRC channel on Freenode.

**Comment by iafan** [comment]
Closing this as I believe this was fixed. Feel free to reopen if necessary.
