### ISSUE TITLE
Required functionality for third party sync plugins

### ISSUE THREAD

**Issue by dragosv** [evernote/serge#101]
In order to interact with other providers, the following functionality is needed

- [x] Ability to rewrite ts path, as the plugins expect a specific pattern 
- [x] Flexible xliff 1.2 Serializer, as the xliff format is a better format for some providers

**Comment by dragosv** [comment]
Implemented as part of
1. https://github.com/evernote/serge/pull/72 Added rewrite ts path (absolute/relative) phases for replace_strings
2. https://github.com/evernote/serge/pull/74 after_serialize_ts_file, before_deserialize_ts_file phases, allowing for filtering or fixing issues with the received ts files or corrections on the generated ts files
3. https://github.com/evernote/serge/pull/77 Generic xslt (https://www.w3.org/Style/XSL/) replacement plugin
4. https://github.com/evernote/serge/pull/78 Xliff 1.2 Serializer that is meant to be extended using the apply_xslt plugin

**Comment by dragosv** [comment]
Blocks https://github.com/dragosv/serge-plugins (Plugins allowing integration between Serge and various Translation Software - Open Source / Commercial)

**Comment by iafan** [comment]
All relevant PRs have been merged. Nice work, Dragos!
