### ISSUE TITLE
Translation services testing support

### ISSUE THREAD

**Issue by dragosv** [evernote/serge#103]
Pootle has no code coverage.

**Comment by iafan** [comment]
I provided some of my concerns about the suggested implementation here: https://github.com/evernote/serge/pull/93#issuecomment-503321951

There's no way to do real repeatable tests against real translation service instances, and mocking these will result in testing mocks. Let's close this ticket, and if there are good ideas on how to implement better code coverage _and_ make tests meaningful without mocking too much, let's discuss them in somewhat more detail before diving into action.
