### ISSUE TITLE
msgctxt keyword for each string

### ISSUE THREAD

**Issue by zhukic** [evernote/serge#111]
Hi. 

I use Serge in conjunction with Smartcat translation server.

Is it possible to add all identifiers with `msgctxt` keyword for each string into all .po files because Smartcat requires `msgctxt` to show id along with source string as shown below ("Select" - source string, "intro_common_choose" - id)?
![image](https://user-images.githubusercontent.com/10047598/52563986-f28b9100-2e13-11e9-9709-c537e1905587.png)

Thanks.

**Comment by iafan** [comment]
This is something that will be handled by https://github.com/evernote/serge/issues/89

Note that there are users that paired Serge with Smartcat, and this setup works just fine. So exposing all keys as `msgctxt` is not actually _required_ (e.g. sync won't break).

Btw, does Smartcat show the developer comments from the .po? This is where all extracted keys currently show up by default.

**Comment by zhukic** [comment]
Yes, Smartcat shows the developer comments from .po files, but the way Smartcat does it is not convenient. For each string, you need to click some button to see the comments while `msgctxt` appears right below the source string.

Thanks.
