### ISSUE TITLE
Typo bug: DROP index items_file_id_string_id after CREATE

### ISSUE THREAD

**Issue by mmcx** [evernote/serge#125]
Typo bug:

-DROP INDEX IF EXISTS items_file_id_string_id;
+DROP INDEX IF EXISTS strings_string_context;

https://github.com/evernote/serge/blob/7fa16fa26ad98b9bb36d5bdd499738e3753ccd4e/lib/Serge/sqlite_schema.sql#L65

**Comment by iafan** [comment]
Fixed. Thanks for reporting!
