### ISSUE TITLE
Optionally enable relaxed JSON parsing in json_parser

### ISSUE THREAD

**Issue by prat0088** [evernote/serge#13]
I'm using json_parser and we have many, many files that have trailing commas.  This breaks the current implementation because the official JSON spec does not prohibit trailing commas.  Rather than write a custom parser or impose a change on our developers, it would be nice to have an option to enable [relaxed mode](http://search.cpan.org/~makamaka/JSON-2.90/lib/JSON.pm#relaxed).

**Comment by iafan** [comment]
I decided not to introduce any options, and just support relaxed parsing by default. This is backwards compatible.
