### ISSUE TITLE
Each <trans-unit> sets "approved=yes" for untranslated strings

### ISSUE THREAD

**Issue by carusology** [evernote/serge#136]
##### Background

This is a **bug**.

According to the XLIFF file spec, the `approved` attribute on the `<trans-unit>` element tracks an approvers "final review" status ([Source](https://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#approved)):

> #### `approved`
> **Value description:** Approved - Indicates whether a translation is final or has passed its final review.
> **Boolean:** `yes` or `no`.
> **Default value:** `no`
> **Used in:** [`<trans-unit>`](https://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#trans-unit), [`<bin-unit>`](https://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#bin-unit)

However, the current implementation of [the `serialize_xliff.pm` XLIFF serializer](https://github.com/evernote/serge/blob/master/lib/Serge/Engine/Plugin/serialize_xliff.pm) sets `approved=yes` for any string that isn't fuzzy-matched to an existing translated string ([Source](https://github.com/evernote/serge/blob/017d8140def675e0c7ab4ad81b75845ded282607/lib/Serge/Engine/Plugin/serialize_xliff.pm#L57-L61)).

This doesn't make sense. We shouldn't be setting the `approved` attribute at all in situations where the string hasn't been translated - fuzzy matched or not. There's nothing that can be "approved" at that point.

##### Task

Update the `serialize_xliff.pm` serializer to no longer set this attribute if the string isn't translated at all.

**Comment by iafan** [comment]
So, in other words, 'approved' attribute should be set to 'no' regardless of the fuzzy status if the translation (`$unit->{target}`) is empty. I think it makes sense. Feel free to provide a PR.

**Comment by carusology** [comment]
Well, not _quite_. The `approved` attribute is _optional_ ([Source](https://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#trans-unit)):

> `<trans-unit>`
> Translation unit - The `<trans-unit>` elements contains a `<source>`, `<target>` and associated elements.
>
> The required `id` attribute is used to uniquely identify the `<trans-unit>` within all `<trans-unit>` and `<bin-unit>` elements within the same `<file>`. The optional `approved` attribute indicates whether the translation has been approved by a reviewer. ... others ...
>
> **Required attributes:** `id`.
> **Optional attributes:** `approved`, ... others ...

I was suggesting omitting it entirely when no translation exists because it's irrelevant. However, since the default for `approved` is "no" ([Source](https://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#approved)), it's logically the same thing.

**Comment by carusology** [comment]
Thanks @iafan! Closed via #137.
