### ISSUE TITLE
Docs no longer easily accessible

### ISSUE THREAD

**Issue by natep** [Evernote/serge#148]
Sorry to hear that this project is potentially being sunsetted, especially since we just started using it a few months ago.

In the meantime, it seems that the serge.io site just redirects to this repo now. So there isn't any straightforward way to view the Serge docs. Any intention of hosting them somewhere?

**Comment by emdotem** [comment]
Hello @natep, unfortunately we have no plan to host the documentation back online. 

Everything is public though, you can take a look at the [website](https://github.com/Evernote/serge-website) ;-) 

Hope this help, 

Best
