### ISSUE TITLE
Add `serge import` support for .plist parser (export keys in parser callback)

### ISSUE THREAD

**Issue by mruthvend2l** [evernote/serge#16]
Wondering if iOS .stringsdict files are not supported yet, not planned to be supported, or should be supported but aren't working. .strings doesn't catch these files (naturally) and I thought they were a pretty close fit for .plist, since the structure is very similar, but I get "ERROR: Parser plugin didn't provide a key value in a callback. Importing translations with this plugin is not possible."

**Comment by iafan** [comment]
Yes, these are supposed to be parsed with [.plist parser](https://serge.io/docs/plugins/parser/parse_plist/). This plugin doesn't currently export .plist keys as separate entities, so `serge import` with this plugin will fail. Adding import support for this plugin is pretty easy, and I'll do this today.

**Comment by iafan** [comment]
Should be good now.

**Comment by mruthvend2l** [comment]
Sorry for the delay, got side-tracked. Thanks for the super-prompt response.
