### ISSUE TITLE
Serge::Engine::Plugin::parse_yaml errors

### ISSUE THREAD

**Issue by erikogan** [evernote/serge#17]
Attempting to use `parse_yaml` results in errors: 

```
ERROR: Parser plugin didn't provide a key value in a callback. Importing translations with this plugin is not possible.
```

I believe this is because it is passing arguments to the callback in the wrong order. In particular it is passing the key path as the third argument, and `Serge::Importer::parse_source_file_callback` uses that argument as the hint. 

`parse_yaml` is also only passing 5 arguments to the callback, which suggests to me it was written for a different version of the parser API.

**Comment by iafan** [comment]
No, it's because it doesn't pass the sixth (optional) parameter, which is a file-unique key. Because of this, `serge import` with this parser won't work. I can add this support tomorrow — it's trivial. The reason I didn't add it initially for all parsers is that we internally don't use `serge import`.

**Comment by erikogan** [comment]
Just so I’m sure I understand what you’re saying: The parser should be passing a unique key for each file, and that’s used as the base of the key/path for the strings in that file?

**Comment by iafan** [comment]
> unique key for each file

A unique key for each string within any given file, to be more precise.

This key value is only used for source<=>translation alignment during import, and technically can be any string. Ideally a key value would be tolerant to the order in which strings appear in the file. For YAML, constructed path is a nice candidate for such key values, provided the path stays the same for both source and localized copy of the file (so in case of Ruby-ob-Rails localization file format style where top node is the name of the language, we need to address #19 to make sure paths can be used for string alignment).

**Comment by erikogan** [comment]
Any update on this? I was hoping to work on #19 this week, and while they’re not dependent I’d prefer to see where you’re going with this before diving into that issue.

**Comment by pchew-change** [comment]
👍  thanks for keeping me updated!

**Comment by iafan** [comment]
@erikogan Your PR addresses the issue, assuming you will fix it according to my comments (use path for both $hint and $key callback params). So my assumption was that you were going to update the PR so that I could merge it.

**Comment by erikogan** [comment]
Whoops, my misunderstanding. When I first read your comments here I thought you wanted to take it in a different direction. I’m happy to update and push.

**Comment by iafan** [comment]
Thanks, Eric! I merged your PR.

**Comment by iafan** [comment]
I'm closing this issue now, as `parse_yaml` can now be used in `serge import` and you're not expected to see the originally reported error, but #19 is what needs to be implemented to actually import data from Ruby on Rails YAML files.
