### ISSUE TITLE
Traversing YAML data before import?

### ISSUE THREAD

**Issue by erikogan** [evernote/serge#19]
The root of the data in our YAML files is the locale of the data:

```yaml
en-US:
  actual_data:
    starts: one level down
```

When we import this data using `parse_yaml`, it creates a string with `en-US/actual_data/starts` as its path. It seems like this should be `actual_data/starts`. I’ve been poking around in the documentation and code, and I don’t see an easy way to make this happen. I’m happy to modify the plugin to take an option specifying a path to traverse in each file, but I wanted to ask if I’m going about this the wrong way before I started. 

(Also: our JSON data is similarly structured, so I’m hoping there is an easier way)

**Comment by erikogan** [comment]
Caveat: This assertion is also based on my misunderstanding of the bug in `parse_yaml` raised in #17. It may be completely moot once that is fixed.

**Comment by iafan** [comment]
I think to address this in the most useful manner (for real-life situations like localizing Ruby-on-Rails apps and allowing to initially import translations from RoR localization files) we could introduce a new `yaml_mode` option similar to what we have [in the XML parser](https://serge.io/docs/plugins/parser/parse_xml/#sel:I2NvZGVfMC9zcGFuLjIzMzMvQC0jY29kZV8wL3NwYW4uMjM2MC9AOjE). This setting would have two possible values: `generic` (default; would fall back to the current behavior) and `rails`.

In such `rails` mode:

1. the parser would ignore the root node name, assuming it's a language name, and exclude it from the built `$path` value. This would allow us to use path as a key callback value for `serge import` to work properly (an issue raised in #17);
2. when constructing the localized YAML file, the parser would replace the name of the root node with the target language name.

**Comment by erikogan** [comment]
Perfect. This is (similar to) what I thought originally, before saying, “I wonder if I can abstract it a bit to make it more generally useful.” But I was likely future-tripping. If a more general form of the `yaml_mode` needs to be added we can cross that bridge when we come to it.

So in the `generic` case the key argument passed to the callback would be the whole path, whereas in `rails` it would trim the locale from the head of the key. That makes sense. I haven’t looked at the code that constructs the localized YAML file, I’ll do that now.

**Comment by erikogan** [comment]
This issue has been resolved by PR #20.
