### ISSUE TITLE
How could I delete the trailing path delimiter when generating output file?

### ISSUE THREAD

**Issue by buptfarmer** [evernote/serge#22]
%PATH%           - file path including trailing path delimiter

In an android project work with serge serializer, the folder name is kind like "values-%lang%"
but %PATH%  including trailing path delimiter with which %PATH%-%lang% only produce "values/-en"
how could I delete the trailing path delimiter when generating output file?

**Comment by iafan** [comment]
Since the path to `values-xx` folders is always known and these types of folders aren't nested, you can usually specify the path directly. Here's a typical setting for localizing android projects:

```
    source_dir                    /path/to/app/res/values
    source_match                  strings\.xml$
    output_file_path              /path/to/app/res/values-%LOCALE:ANDROID%/%FILE%
```

Would this approach work for you?

**Comment by buptfarmer** [comment]
This a good solution right now. And for different "values" folders need translation. create different job will handle that situation. 
Thanks.
