### ISSUE TITLE
How to I convert all the android text xml into iOS strings?

### ISSUE THREAD

**Issue by buptfarmer** [evernote/serge#24]
#serge IRC channel on Freenode.  seems nobody on that .
![image](https://cloud.githubusercontent.com/assets/4084663/16610414/ae1eb772-438d-11e6-9492-cc67394f95ba.png)

So i post the question here. 
Using the previous android_ios project working with serge,  As the development of the android project is much faster than the ios project, so after the translation of android project finished, I would like to use all the translation in ios project.  
By far, it seems that I have to create all the keys in ios project same with the android project, which is very tedious and huge work.  
Can I generate all *.strings files from the *.xml files in order to get all the texts with serge? 
Thank you.

**Comment by iafan** [comment]
I'm in IRC (nickname: `iafan`) during most of the day (I'm in PDT /GMT-7/ time zone). Feel free to ping me whenever you see me online.

Serge is not a tool to convert between different file formats. iOS and Android apps are usually pretty different, so there's no 100% match in strings. For example, strings with placeholders would be different for iOS and Android, unless you use some custom cross-platform format for placeholders.

Though one can technically write a plugin that would do the conversion at the time you run `serge localize`, I'd suggest doing such format conversion outside the Serge localization workflow. It can be a script that takes one android XML file and generates one corresponding .strings file at the specified path. You can take Serge's [Android XML parser code](https://github.com/evernote/serge/blob/master/lib/Serge/Engine/Plugin/parse_android.pm) as a base for this script.

Once you have the .strings file generated from your XML files, you can localize them with Serge the way I showed before — Serge will reuse translations there just fine.

**Comment by buptfarmer** [comment]
We have little common day time.  (I'm in GMT+8/ time zone) 
I found that parse_android plugin parse <string-array> into "key:item", but ios project use array this way : key[0], key[1], key[2]  , how could ios key[0] format reuse the android translation with "key:item" format?

android xml code
```
    <string-array name="day_of_week">
        <item>"Mon"</item>
        <item>"Tue"</item>
        <item>"Wed"</item>
        <item>"Thu"</item>
        <item>"Fri"</item>
        <item>"Sat"</item>
        <item>"Sun"</item>
    </string-array>
```
ios strings code
```

/*  */
"day_of_week[0]" = "Mon";

/*  */
"day_of_week[1]" = "Tue";

/*  */
"day_of_week[2]" = "Wed";

/*  */
"day_of_week[3]" = "Thu";

/*  */
"day_of_week[4]" = "Fri";

/*  */
"day_of_week[5]" = "Sat";

/*  */
"day_of_week[6]" = "Sun";
```

![image](https://cloud.githubusercontent.com/assets/4084663/16640247/02814c58-4429-11e6-829d-e3ea51f1e838.png)

**Comment by iafan** [comment]
Mapping of Android<=>iOS keys is totally up to you (and your conversion script). Serge only uses keys as _hints_ (comments that provide additional context to translators). Even if your keys differ, Serge will still reuse the translations.
