### ISSUE TITLE
Can you please add installation instruction for Windows?

### ISSUE THREAD

**Issue by whereisjim** [evernote/serge#28]
I'm not familiar with UNIX base. 
I started reading below page then got stuck in Step #3.
https://serge.io/download/#sel:ZGl2L2Rpdi4yL2NvZGUuMS9ALjE6MS0qOjQ0

Is there way to add 'Step 3. Install Dependencies for Windows' in this page for Windows user?

**Comment by iafan** [comment]
I'm actually using Windows as my primary OS, so I can definitely help you with the setup.

The `git pull ...` step works on Windows, provided you have [Git](https://git-scm.com/) installed. Istead of pulling the project from Github, you can also use [option B](https://serge.io/download/#b-download-latest-stable-snapshot) to simply download Serge release snapshot, or download [current master](https://github.com/evernote/serge/archive/master.zip). Note that you may need Git later anyway if you have any Git repositories with localizable files).

Ignore the [Install Dependencies](https://serge.io/download/#step-3-install-dependencies) step for now and try installing the dependencies. If you get an error during installing Perl modules, please provide details, and we'll see what needs to be installed.

Based on this, I'll have a clearer picture of what and how to add to documentation.

**Comment by jmkimTSI** [comment]
I installed Strawberry Perl under c:\strawberry and the bin folder is part of PATH.
Serge is copied to c:\serge.
From CMD, I ran 'serge' then I'm getting below error:

Can't locate Config/Neat/Inheritable.pm in @INC (you may need to install the Con
fig::Neat::Inheritable module) (@INC contains: C:\serge\vendor\lib C:\serge\lib
C:\serge\extlibs\lib\perl5 c:/Strawberry/perl/site/lib c:/Strawberry/perl/vendor
/lib c:/Strawberry/perl/lib .) at C:\serge\lib/Serge/Config.pm line 7.
BEGIN failed--compilation aborted at C:\serge\lib/Serge/Config.pm line 7.
Compilation failed in require at C:\serge\lib/Serge/Config/Collector.pm line 8.
BEGIN failed--compilation aborted at C:\serge\lib/Serge/Config/Collector.pm line
 8.
Compilation failed in require at C:\serge\lib/Serge/Application.pm line 10.
BEGIN failed--compilation aborted at C:\serge\lib/Serge/Application.pm line 10.
Compilation failed in require at c:\serge\bin\serge line 12.
BEGIN failed--compilation aborted at c:\serge\bin\serge line 12.

Looks like I'm missing some module. I'm trying to figure it out how to install that particular module, but since I never used Perl, It would be great if someone can help me out.
TIA.

**Comment by whereisjim** [comment]
I installed Strawberry Perl under c:\strawberry and the bin folder is part of PATH.
Serge is copied to c:\serge.
From CMD, I ran 'serge' then I'm getting below error:

Can't locate Config/Neat/Inheritable.pm in @INC (you may need to install the Con
fig::Neat::Inheritable module) (@INC contains: C:\serge\vendor\lib C:\serge\lib
C:\serge\extlibs\lib\perl5 c:/Strawberry/perl/site/lib c:/Strawberry/perl/vendor
/lib c:/Strawberry/perl/lib .) at C:\serge\lib/Serge/Config.pm line 7.
BEGIN failed--compilation aborted at C:\serge\lib/Serge/Config.pm line 7.
Compilation failed in require at C:\serge\lib/Serge/Config/Collector.pm line 8.
BEGIN failed--compilation aborted at C:\serge\lib/Serge/Config/Collector.pm line
8.
Compilation failed in require at C:\serge\lib/Serge/Application.pm line 10.
BEGIN failed--compilation aborted at C:\serge\lib/Serge/Application.pm line 10.
Compilation failed in require at c:\serge\bin\serge line 12.
BEGIN failed--compilation aborted at c:\serge\bin\serge line 12.

Looks like I'm missing some module. I'm trying to figure it out how to install that particular module, but since I never used Perl, It would be great if someone can help me out.
TIA.

**Comment by whereisjim** [comment]
Update.
**Error #01**
Can't locate Config/Neat/Inheritable.pm in @INC (you may need to install the Config::Neat::Inheritable module)
**Resolution:** 
downloaded 'Config-Neat-1.101.tar.gz' file from: http://search.cpan.org/~afan/Config-Neat-1.101/lib/Config/Neat/Inheritable.pm
Extracted files and copied under 'c:\Strawberry\perl\site\' folder. Copied 'bin', 'lib' and etc folders and not the 'Config-Neat-1.101' folder level.

**Error #02**
Can't locate Tie/IxHash.pm in @INC (you may need to install the Tie::IxHash module)
**Resolution**
downloaded 'Tie-IxHash-1.23.tar.gz' file from: http://search.cpan.org/~chorny/Tie-IxHash-1.23/lib/Tie/IxHash.pm
Extracted files and copied under 'c:\Strawberry\perl\site\' folder. Copied 'bin', 'lib' and etc folders

After above two stpes, the Serge is working now.
I don't know if this is the right steps to install modules for Perl, but it would be great to add these instruction for Perl newbie.

**Comment by iafan** [comment]
@whereisjim installing modules by manually copying them into specific folders is the last resort — usually you don't want to do that.

As per installation instructions, these are the two commands that can install all the missing Perl dependencies for you:

```
cpan App::cpanminus
cpanm --installdeps .
```

I recommend running them just in case you have some other missing dependencies (which are used e.g. in certain parsers)

**Comment by whereisjim** [comment]
@iafan Thank you. I don't know why it didn't work before, but I tried that command now and it works now.

Suggestion.
Right below the Step 3., the sentences starts as "Some dependency Perl ....". If you can change that line as "[Linux users ONLY] Some dependency Perl...".
I think that might helped for me I think.

Anyway, thank you.

**Comment by whereisjim** [comment]
Another thought. Actually, that might still confuse user. That line might mislead user that the whole step 3 is only for Linux user.
Anyway, if you can use different font or color for the first section of Step 3 as Linux user only might help.

**Comment by iafan** [comment]
[I updated the documentation.](https://serge.io/download/#sel:I3N0ZXB+MzF+aW5zdGFsbH5wcmVyZXF1aXNpdGVzfmxpbnV4fm9ubHkvYS1kaXYvZGl2LjI6NDI) Hope it is clearer now.

**Comment by whereisjim** [comment]
Perfect!!
Thank you!
