### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by liuwin7** [evernote/serge#33]
After i fellowed what the serge.io says, I want use the command serge to verify the correction about my installation process. Unfortunately I got  an error. Here's
`Can't locate Config/Neat/Inheritable.pm in @INC (you may need to install the Config::Neat::Inheritable module) (@INC contains: /Users/tropsci/serge/serge-1.1/bin/../vendor/lib /Users/tropsci/serge/serge-1.1/bin/../lib /Users/tropsci/serge/serge-1.1/bin/../extlibs/lib/perl5 /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/tropsci/serge/serge-1.1/bin/../lib/Serge/Config.pm line 7.
BEGIN failed--compilation aborted at /Users/tropsci/serge/serge-1.1/bin/../lib/Serge/Config.pm line 7.
Compilation failed in require at /Users/tropsci/serge/serge-1.1/bin/../lib/Serge/Config/Collector.pm line 8.
BEGIN failed--compilation aborted at /Users/tropsci/serge/serge-1.1/bin/../lib/Serge/Config/Collector.pm line 8.
Compilation failed in require at /Users/tropsci/serge/serge-1.1/bin/../lib/Serge/Application.pm line 10.
BEGIN failed--compilation aborted at /Users/tropsci/serge/serge-1.1/bin/../lib/Serge/Application.pm line 10.
Compilation failed in require at ./serge line 12.
BEGIN failed--compilation aborted at ./serge line 12.`
what's wrong with it？

**Comment by iafan** [comment]
It seems that you don't have `Config::Neat::Inheritable` dependency module installed.  Please see this step: http://serge/download/?unix/stable#step-3-install-dependencies

Specifically, make sure that `sudo cpanm --installdeps .` command generates no errors (you can run it once again after installing dependencies, and it will just report that you have all the dependencies.

If you have trouble installing dependency modules, please share the output of the `sudo cpanm --installdeps .`

**Comment by liuwin7** [comment]
I use Mac OS, not UNIX.

**Comment by liuwin7** [comment]
And, the command `sudo cpanm App::cpanminus` tells me that the the module has been installed already.
```
--> Working on App::cpanminus
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz ... ^CFAIL
! Download cancelled.
! Failed to fetch distribution App-cpanminus-1.7042
topsci:serge-1.1 tropsci$ cpanm Config::Neat::Inheritable
Config::Neat::Inheritable is up to date. (1.204)
```
Maybe, my `cpanm` environment is not correct, but i do not know what's wrong with it. 
Could you help me?

**Comment by liuwin7** [comment]
@iafan

**Comment by iafan** [comment]
Could you please provide a full output of the `sudo cpanm --installdeps .` command? This is to ensure there are no other missing dependencies. As a part of this dependency installation, an entire `Config::Neat` package needs to be installed, not just the `Config::Neat::Inheritable` module.

Would it be possible for you to jump into our [IRC chat](https://serge.io/contact/)?

**Comment by liuwin7** [comment]
@iafan 
There is a module XML is failed when running the command `sudo cpanm --installdeps .  `. And I use the option `--force` to install it. Other modules are installed successfully.

And now I use the command `sudo cpanm Config::Neat` and it shows that ` Config::Neat is up to date. (1.204) `

**Comment by liuwin7** [comment]
@iafan 
After installed the module XML, when i use `sudo cpanm --installdeps .`, showing that 
```
--> Working on .
Configuring /Users/tropsci/serge/serge-1.1 ... OK
<== Installed dependencies for .. Finishing.
```

**Comment by liuwin7** [comment]
@iafan 
Maybe I've resolve the problem. My assumption is right. The environment about my Perl is not so good, especially the PATH. Owe to the MacPort and the HomeBrew, i have modified the PATH for them and the system `Perl` cannot been search firstly. So, I uninstall all the `Perl`s other than the system version. The system version `Perl` can be search firstly, as well as its suited library.

Exciting when the `serge help` prompts on the Terminal. 

Thank you!

**Comment by iafan** [comment]
Cool. That kind of issue would definitely take some time to debug remotely. I'm glad that it now works for you.
