### ISSUE TITLE
Linking `serge` to `/usr/bin` failed on Mac OS X 10.11 El Capitan and later

### ISSUE THREAD

**Issue by liuwin7** [evernote/serge#34]
Owe to the new protection strategy on Mac OS X 10.11 EI Capitan and later, System Integrity Protection(SIP), user haven't the permission to write access the directory `/usr/bin`, even the root role.

So, [Create a symlink to serge binary](https://serge.io/download/?mac/stable#sel:ZGl2L2Rpdi4yL2NvZGUuNS9ALWRpdi9kaXYuMjo1OQ) in the guide for the Serge installation on Mac is not correct.

Please correct it. Maybe the `/usr/local/bin/` is a good candidate.

**Comment by iafan** [comment]
Thanks for letting us know. So did `/usr/local/bin/serge` work for you?

**Comment by liuwin7** [comment]
@iafan 
Yes.

**Comment by liuwin7** [comment]
This [article](http://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/) shows what is SIP.

**Comment by iafan** [comment]
[I updated the documenation accordingly](https://serge.io/download/?mac/stable#sel:ZGl2L2Rpdi4yL2NvZGUuNS9ALjE6MTEtKjozMQ)

**Comment by liuwin7** [comment]
Cool.
