### ISSUE TITLE
.pot parser can't parse files with "#~" lines

### ISSUE THREAD

**Issue by enkore** [evernote/serge#41]
Some tooling* apparently generates lines starting with `#~` which causes the parser to fail at Serge/Engine/Plugin/parse_pot.pm line 168. Another instance that doesn't seem to be received well are lines like `#| msgid...` which are mentioned in the gettext docs (the aforementioned kind isn't).

Reproduced on latest master branch.

This is a really impressive tool. Great work!

\* I suspect Lokalize

**Comment by iafan** [comment]
@enkore, thanks for the report! Do you have an example of such a file to test against?
