### ISSUE TITLE
Doubly escaped strings

### ISSUE THREAD

**Issue by MPomeroy** [evernote/serge#48]
Hi,

We're working on integrating serge into our development process and in general things are going very well. However, we're running into an issue where serge is escaping our escape characters when processing Apple .strings files with the .strings plugin.

It seems like serge is importing the files from our codebase with the escape characters intact, but then escaping our escape characters when we run localize.

Is there (or could there be) a way to turn off character escaping?

**Comment by iafan** [comment]
Can you please share and example of the .strings file that I could use to reproduce the problem? (You can trim it down to just one or two problematic lines.)

**Comment by MPomeroy** [comment]
Of course, thanks for the prompt response.

From the base strings file:

    /* Sample strings with escapes */
    "dateslist.nothingdue" = "Nothing due.";
    "dateslist.nothingdue.today" = "Nothing due today.";

From the french translation:

    /* Sample strings with escapes */
    "dateslist.nothingdue" = "Rien n\'est dû.";
    "dateslist.nothingdue.today" = "Rien n\'est dû aujourd\'hui.";

**Comment by iafan** [comment]
I can confirm that if one has `\'` in the translation, in the generated file it will be presented as `\\'`.

According to [Apple's documentation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html) one doesn't need to escape apostrophes:

> ### Using Special Characters in String Resources
> Just as in C, some characters must be prefixed with a backslash before you can include them in the string. These characters include double quotation marks, the backslash character itself, and special control characters such as linefeed (\n) and carriage returns (\r).

So if the above it's true, then what Serge currently does is kind of expected: it detects a backslash not followed by any of the special characters, and escapes it by itself.

So I guess my next question is: why do you have apostrophes escaped, and can you try simply converting some `\'` to `'` and see if this change has any effect on your application? If it doesn't, it just makes sense to convert these once through all resources.

**Comment by iafan** [comment]
I also checked our own iOS and macOS resource files, and we have these strings that work just fine:

```
"'%@' is not a valid email address." = "'%@' n'est pas une adresse email valide.";
```

**Comment by MPomeroy** [comment]
That makes perfect sense, I just tested it and our app builds fine without the escape characters. I'm not certain why they were included in the file in the first place...

I will do as you suggest and clean up the strings on my end. Thanks for looking into this!
