### ISSUE TITLE
Uppercase letters in language names are unsupported

### ISSUE THREAD

**Issue by iafan** [evernote/serge#5]
If one defines a language with uppercase text in it, e.g. `de-DE`, then Serge can't properly find a translation in a database.

While it's recommended to use ISO language codes (which are lowercase), Serge should support any kinds of strings as language names.

**Comment by julen** [comment]
For completeness, here's a relevant [excerpt from IETF's BCP 47 on Language Tags](http://tools.ietf.org/rfc/bcp/bcp47.txt):

>    Although case distinctions do not carry meaning in language tags,
   consistent formatting and presentation of language tags will aid
   users.  The format of subtags in the registry is RECOMMENDED as the
   form to use in language tags.  This format generally corresponds to
   the common conventions for the various ISO standards from which the
   subtags are derived.

>   These conventions include:

>   o  [ISO639-1] recommends that language codes be written in lowercase
      ('mn' Mongolian).

>   o  [ISO15924] recommends that script codes use lowercase with the
      initial letter capitalized ('Cyrl' Cyrillic).

>   o  [ISO3166-1] recommends that country codes be capitalized ('MN'
      Mongolia).

>   An implementation can reproduce this format without accessing the
   registry as follows.  All subtags, including extension and private
   use subtags, use lowercase letters with two exceptions: two-letter
   and four-letter subtags that neither appear at the start of the tag
   nor occur after singletons.  Such two-letter subtags are all
   uppercase (as in the tags "en-CA-x-ca" or "sgn-BE-FR") and four-
   letter subtags are titlecase (as in the tag "az-Latn-x-latn").
