### ISSUE TITLE
CSV Parser plugin

### ISSUE THREAD

**Issue by prat0088** [evernote/serge#52]
Creating an issue to track discussion related to parse_csv, a module I'm working on.

It's mostly complete now.  I'm just working on adding comments and a few more corner cases to the tests.

Notes:

- It is basically key-value, stored as CSV.
- I didn't create it with the intent of using multiple columns as a translation source because that's not what I need it for, but I wouldn't rule it out in the future.
- My usage assumes the key column values are unique within the .csv file, but I will try not to code that assumption into the plugin, if possible.
- It will preserve extra columns in the CSV file.

An example config:
```

        parser
        {
            plugin            parse_csv
            data
            {
                column_key    KEY
                column_string STRING
                # Also column_context, column_comment, delimiter
           }
         }
```

Feedback is appreciated.

**Comment by prat0088** [comment]
As part of this change I'd like to test the errors my parser generates, but I don't see a way with the current t/engine.t design.

What I'd like to do is create t/lib/Test/Engine.pm that will have a method that looks something like `job_completes_ok('engine/parse_csv/01');` that contains all the code under 'subtest' in t/engine.t.  t/enigne.t would be refactored to use that method.

Existing tests would remain as-is, but I will create a test in t/engine/parse_csv/01/test.t with [Capture::Tiny](http://search.cpan.org/~dagolden/Capture-Tiny-0.44/):

```
my $output = capture_merged {
    job_completes_ok('engine/parse_csv/01');
}

like $output, qr/Error: Too much C, not enough S or V/, "parse_csv reports excessive Cs correctly;
```

This would give future parser modules the opportunity to test error messages and other output.

@iafan Would appreciate your comments on the direction I'm headed regarding the changes to the test suite.

**Comment by iafan** [comment]
Closing the issue that has been implemented.
