### ISSUE TITLE
What is the 'output_encoding' value for escaped Unicode (ASCII+UCN \U)?

### ISSUE THREAD

**Issue by whereisjim** [evernote/serge#60]
What is the 'output_encoding' value for escaped Unicode (ASCII+UCN \U) and native encoding such as SHIFT_JS?

The configuration reference document shows below:
# Sample values: UTF-8, UTF-16, UCS-2, UCS-4
Are these the only supported encoding or does Serge supports more? If so, can we have some more supported encoding somewhere or in this reference page?

**Comment by iafan** [comment]
Serge internally uses [Encode](http://perldoc.perl.org/Encode.html) Perl module, so it should support all its encodings. Here's the list I get on my machine:

```
7bit-jis, AdobeStandardEncoding, AdobeSymbol, AdobeZdingbat,
MIME-B, MIME-Header, MIME-Header-ISO_2022_JP, MIME-Q, MacArabic,
MacCentralEurRoman, MacChineseSimp, MacChineseTrad, MacCroatian,
MacCyrillic, MacDingbats, MacFarsi, MacGreek, MacHebrew, MacIcelandic,
MacJapanese, MacKorean, MacRoman, MacRomanian, MacRumanian,
MacSami, MacSymbol, MacThai, MacTurkish, MacUkrainian,
UCS-2BE, UCS-2LE, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE,
UTF-32LE, UTF-7, ascii, ascii-ctrl, big5-eten, big5-hkscs, cp1006, cp1026,
cp1047, cp1250, cp1251, cp1252, cp1253, cp1254, cp1255, cp1256, cp1257, 
cp1258, cp37, cp424, cp437, cp500, cp737, cp775, cp850, cp852, cp855,
cp856, cp857, cp858, cp860, cp861, cp862, cp863, cp864, cp865,
cp866, cp869, cp874, cp875, cp932, cp936, cp949, cp950, dingbats,
euc-cn, euc-jp, euc-kr, gb12345-raw, gb2312-raw, gsm0338, hp-roman8,
hz, iso-2022-jp, iso-2022-jp-1, iso-2022-kr, iso-8859-1, iso-8859-10,
iso-8859-11, iso-8859-13, iso-8859-14, iso-8859-15, iso-8859-16,
iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6,
iso-8859-7, iso-8859-8, iso-8859-9, iso-ir-165, jis0201-raw, jis0208-raw,
jis0212-raw, johab, koi8-f, koi8-r, koi8-u, ksc5601-raw, nextstep, null,
posix-bc, shiftjis, symbol, utf-8-strict, utf8, viscii
```

You can also run the following script on your machine to get the list:
```perl
use Encode;
print join(", ", sort Encode->encodings(":all")), "\n";
```

In your case, I guess you're interested in `shiftjis` encoding.

**Comment by iafan** [comment]
Also, when it comes to escaping Unicode, this is more of a  parser job to do such serialization/deserialization. For example, `parse_properties` parser natively supports [Java-specific encoding](https://serge.io/docs/plugins/parser/parse_properties/#sel:I2NvZGVfMC9zcGFuLjYxNi9ALSNjb2RlXzAvc3Bhbi42NDAvQDox).

**Comment by whereisjim** [comment]
Thank you iafan!

**Comment by whereisjim** [comment]
Thank you.
