### ISSUE TITLE
Hard-coded references to Pootle in Sync.pm

### ISSUE THREAD

**Issue by prat0088** [evernote/serge#62]
Custom sync plugins can be created, but there are two hard-coded references to Pootle.  The logs become misleading when using a non-Pootle back-end.

https://github.com/evernote/serge/blob/ba6b1b11ebd46eba3522ebe646d4bbbe0a2f0c10/lib/Serge/Sync.pm#L116

https://github.com/evernote/serge/blob/ba6b1b11ebd46eba3522ebe646d4bbbe0a2f0c10/lib/Serge/Sync.pm#L143

**Comment by iafan** [comment]
Thanks, @prat0088. I updated the wording.
