### ISSUE TITLE
parse_android doesn't support importing

### ISSUE THREAD

**Issue by imankulov** [evernote/serge#7]
Hi! Thanks for making `serge` Open Source!

When trying to import my current Android translations, I get back with a message

```
$ serge import myproject_android.serge

*** /home/pootle/serge-workspace/myproject_android.serge ***



*** [myproject_android]  ***

Preloading properties...
Path to source resources: [/home/pootle/serge-workspace/myproject_android/android/values]
Path to localized resources: [/home/pootle/serge-workspace/myproject_android/android/values-%LOCALE%/%FILE%]
Languages: [af,ar,bg,bn,bn_IN,ca,...,vi,zh_CN,zh_TW]
DB source: [DBI:SQLite:dbname=/home/pootle/serge-workspace/myproject_android.db3]
Preloading cache for job 'myproject_android' in namespace 'myproject_android'...

Updating database from source files...

Scanning directory structure...
Scanned in 0.000882000000000049 sec, 39 files match the criteria
        strings.xml
                        ERROR: Parser plugin didn't provide a key value in a callback. Importing translations with this plugin is not possible.
```

Is that right, you don't support import from Android XML files yet? Is there a workaround to populate the project with already translated strings?

**Comment by iafan** [comment]
Should be fixed now. Try with the version from `master`

**Comment by imankulov** [comment]
It works. Thank you!

**Comment by iafan** [comment]
@imankulov, one small comment on your setup: I'd recommend using canonical lowercase ISO language codes in Serge configs: `bn-in zh-cn zh-tw` and so on. This will allow language-based config macros to work properly. See https://serge.io/docs/configuration-files/reference/ (on this page, search for `%LOCALE%`, `%CULTURE%`, etc.)

**Comment by imankulov** [comment]
Got it. Thanks for the hint
