### ISSUE TITLE
Split Serge into Base and Main

### ISSUE THREAD

**Issue by dragosv** [evernote/serge#88]
In order to extend Serge a library only needs to depend on the Base functionality (Serge::Engine::Plugin::Base::Parser, Serge::Engine::Plugin::Base::Serializer,  Serge::Engine::Plugin::Base::Transform, Serge::Interface::SysCmdRunner, Serge::Plugin::Base::Callback, Serge::Plugin::Base). Hence I propose having a Serge::Base on cpan while the rest (Serge) is not required on cpan.

**Comment by dragosv** [comment]
This is also he standard approach in the .net and java world, to have the interfaces in a separate library.

**Comment by dragosv** [comment]
It will also solve the issue of the documentation on how to install serge not working when trying to install a translation service plugin (https://github.com/dragosv/serge-plugins/issues/4)

**Comment by iafan** [comment]
Closing this as something that won't likely happen. `Serge` module is supposed to be installable at all times, and the originally reported issue has been fixed in https://github.com/evernote/serge/commit/bac6f939780aa1e5e38d92f5d812a4628813e2fa
